version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    networks:
      - backend
    environment:
      - ENV=dev
      - DB_HOST=tcp://db:3306
    tty: true
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    networks:
      - backend
  # redis:
  #   build:
  #     context: .
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: redis
  #   hostname: redis
  #   networks:
  #     - backend

networks:
  backend:
    driver: 'bridge'